#ifndef LOGGING_H
#define LOGGING_H

#include <QLoggingCategory>

// Core systems
Q_DECLARE_LOGGING_CATEGORY(lcWorld)
Q_DECLARE_LOGGING_CATEGORY(lcNetwork)
Q_DECLARE_LOGGING_CATEGORY(lcScript)
Q_DECLARE_LOGGING_CATEGORY(lcAutomation)

// UI systems
Q_DECLARE_LOGGING_CATEGORY(lcUI)
Q_DECLARE_LOGGING_CATEGORY(lcDialog)

// Subsystems
Q_DECLARE_LOGGING_CATEGORY(lcPlugin)
Q_DECLARE_LOGGING_CATEGORY(lcMiniwindow)
Q_DECLARE_LOGGING_CATEGORY(lcText)
Q_DECLARE_LOGGING_CATEGORY(lcLogging)
Q_DECLARE_LOGGING_CATEGORY(lcStorage)
Q_DECLARE_LOGGING_CATEGORY(lcTest)
Q_DECLARE_LOGGING_CATEGORY(lcMXP)

#endif // LOGGING_H
